### ISSUE TITLE
Can't Pull the Function if Function Body Includes Empty Lines

### ISSUE THREAD

**Issue by tonystevenj** [microsoft/delta-kusto#164]
The function created:
![image](https://github.com/microsoft/delta-kusto/assets/47764110/236f8c36-d4e6-423b-aae9-8aa2476d889c)

The error when running Kusto-Delta:
![image](https://github.com/microsoft/delta-kusto/assets/47764110/3d04ae5f-2cab-4b94-a3e5-cb18baa916b5)

The job:
```
  Sync-Playground:
    target:
        adx:
            clusterUri:  <clusterUrl>
            database:  <Database Name>
    action:
        filePath:  <local path>
```
