### ISSUE TITLE
Columns with numeric names are not escaped using ['<name>'] syntax

### ISSUE THREAD

**Issue by cirvine-MSFT** [microsoft/delta-kusto#177]
Some of the tables we work with have numeric column names (e.g. "1" or "0"). We found that delta-kusto does not escape these names appropriately and the commands that are produced or syntatically invalid.

For example, delta-kusto will produce this command
``` kql
.create-merge table TableWithNumberColumns (0:string, 1:string, ['foo']:string) with (folder="", docstring="") 
```
When it should be
``` kql
.create-merge table TableWithNumberColumns (['0']:string, ['1']:string, ['foo']:string) with (folder="", docstring="") 
```

Full steps to reproduce the issue:

Starting with a database called logs, create a table using this command
``` kql
.create table TableWithNumberColumns (['0']:string, ['1']:string, foo:string)
```
Create a parameter file for delta-kusto that will pull the state of the database
``` yaml
failIfDataLoss: true
jobs:
  GetSnapshot:
    target:
      adx:
        clusterUri: to-override
        database: logs
    action:
      pushToConsole: false
      filePath:  logs-delta.kql
tokenProvider:
  azCli: 
    interactive: true
```

delta-kusto produces a delta file that looks like
``` kql
//  Create tables

.create-merge table TableWithNumberColumns (0:string, 1:string, ['foo']:string) with (folder="", docstring="") 
```
Expected that the columns 0, and 1 would be escaped
``` kql
//  Create tables

.create-merge table TableWithNumberColumns (['0']:string, ['1']:string, ['foo']:string) with (folder="", docstring="") 
```
